### ISSUE TITLE
Crash at Intranet

### ISSUE THREAD

**Issue by JohnFai91** [JohnFai91/com.jason.kslo#45]
**To Reproduce**
1. Go  ''Login"
1. See error

**Expected behavior**
It should not crash

**Stacktrace**
Build version: 1.1.3 
Current date: 2021-05-18 13:24:08 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.jason.kslo.parseContent.loggedInParseContent.fragment.LoginFragment$Content.doInBackground(LoginFragment.java:99)
	at com.jason.kslo.parseContent.loggedInParseContent.fragment.LoginFragment$Content.doInBackground(LoginFragment.java:59)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by JohnFai91** [comment]
Still hasn't been fixed

**Comment by JohnFai91** [comment]
Solved in 1.1.4
